title: Lex-Atlas: Covid 19
name: Lex-Atlas: Covid 19
logo: /img/la_biglogo.png
description: null
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
github:
  is\_project\_page:false
