title: "Lex-Atlas: Covid 19"
name: null
logo: /img/la_biglogo.png
description: A global academic project mapping legal responses to COVID-19.
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
github:
  is_project_page: false
